# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class LogLevel(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """LogLevel."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


class State(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """State."""

    NOT_RUNNING = "notRunning"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    CANCELED = "canceled"
    FAILED = "failed"
    DELETED = "deleted"
